<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../upstream/openmir2/src/LoginGate/Services/ClientManager.cs" Link="ClientManager.cs" />
  </ItemGroup>
</Project>
